version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Node: $(node -v) | NPM: $(npm -v)"
      - echo Installing dependencies...
      - |
        if [ -f package-lock.json ]; then
          npm ci --legacy-peer-deps
        else
          npm install --legacy-peer-deps
        fi
  build:
    commands:
      - echo Building the React app...
      - npm run build
  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: no

cache:
  paths:
    - /root/.npm/**/*

